name: GitHub Pages

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build Soluna Runtime
        uses: ./soluna/.github/actions/soluna
        id: build
        with:
          soluna_path: soluna

      - name: Build Extlua Modules
        uses: ./.github/workflows/actions/extlua
        id: extlua
        with:
          project_path: "."

      - name: Build Astro
        uses: withastro/action@v6
        env:
          SITE_BASE: /${{ github.event.repository.name }}/
          SITE_URL: https://${{ github.repository_owner }}.github.io
          SOLUNA_JS_PATH: ${{ steps.build.outputs.SOLUNA_JS_PATH }}
          SOLUNA_WASM_PATH: ${{ steps.build.outputs.SOLUNA_WASM_PATH }}
          SOLUNA_WASM_MAP_PATH: ${{ steps.build.outputs.SOLUNA_WASM_MAP_PATH }}
          EXTLUA_BIN_DIR: ${{ steps.extlua.outputs.EXTLUA_BIN_DIR }}
        with:
          path: website
          node-version: 24
          build-cmd: pnpm run build
          out-dir: dist

  deploy:
    name: Deploy to GitHub Pages
    if: github.actor != 'nektos/act'
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
